scm:
  user: 'github-actions[bot]'
  email: '41898282+github-actions[bot]@users.noreply.github.com'
  username: 'UPDATECLI_GITHUB_ACTOR'
  token: 'UPDATECLI_GITHUB_TOKEN'
  owner: 'rancher'
  repo: 'dartboard'
  branch: 'main'
  commitusingapi: false
  commitmessage:
    squash: true
  mergemethod: 'squash'

repos:
  opentofu:
    owner: 'opentofu'
    repo: 'opentofu'
  kubectl:
    owner: 'kubernetes'
    repo: 'kubernetes'
  helm:
    owner: 'helm'
    repo: 'helm'
  k3d:
    owner: 'k3d-io'
    repo: 'k3d'

vendored_binaries:
  manifest: 'Update vendored binaries versions'
  pipelineid: 'update-vendored-binaries'
  commitmessage:
    type: 'deps'
    scope: 'vendored-binaries'
