apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-files
data:
{{ (.Files.Glob "test-files/*.{js,mjs}").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-lib-files
data:
{{ (.Files.Glob "test-files/lib/*.{js,mjs}").AsConfig | indent 2 }}
