name: K3d Integration Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release/*'
      - 'main'
permissions:
  contents: read
jobs:
  k3d-integration-test:
    name: K3d Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: './go.mod'
          cache: false

      - name: Build Dartboard
        run: make build

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Test Apply - Empty Cluster
        run: |
          ./dartboard --dart=./darts/k3d_empty_cluster_only.yaml apply

      - name: Destroy - Empty Cluster
        if: always()
        run: |
          ./dartboard --dart=./darts/k3d_empty_cluster_only.yaml destroy

      - name: Test Deploy - Full Environment
        run: |
          ./dartboard --dart=./darts/k3d.yaml deploy

      - name: Destroy - Full Environment
        if: always()
        run: |
          ./dartboard --dart=./darts/k3d.yaml destroy
